### ISSUE TITLE
通知時刻が README と実装で違う

### ISSUE THREAD

**Issue by culumn** [aptp/Kud#1]
README では21:00(9pm)、実装では22:00となっている。

- README
>  Notice number of github.com contributions of that day at 9pm and a week's contributions.
https://github.com/aptp/Kud/blame/master/README.md#L10

- slack.go
https://github.com/aptp/Kud/blob/150bff0e8aab6d186811877cce6492aa2e425413/adapter/controller/slack/slack.go#L43

**Comment by natumn** [comment]
更新するの忘れてました。
何時がいいとかある？

**Comment by natumn** [comment]
新しいコミットで対応しました！
https://github.com/aptp/Kud/commit/9d1175276702d7f351239806232fe2543a85c465
報告ありがとう！
